### ISSUE TITLE
OpenMUC not accessible over MavenCentral()

### ISSUE THREAD

**Issue by FXaverZ** [openmucextensions/forecastio#1]
In the current gradle-script OpenMUC is integrated via compile groups, unfortunately the OpenMUC core is not accessible over maven central repository.

Current work around: add a local path to the .jars of OpenMUC:

```
flatDir {
    //Path to .jars of OpenMUC
    dirs '../../build/libs/'
    }
```

I'm not sure, how this issue can be resolved...

**Comment by pichler** [comment]
The dependency can be resolved by installing OpenMUC into the local repository on your system. Download OpenMUC from the [project's website](www.openmuc.org) and install the bundles by executing

```
gradle install
```

Don't foreget to set the right OpenMUC version in the build file of the OpenMUC extension.

**Comment by danielWQ** [comment]
This issue is also explained in the wiki of the bacnet-extension (https://github.com/openmucextensions/bacnet/wiki/How-to-build-and-install-the-driver). Maybe we can find a better place for this howto or copy it to all other related projects.
